'use strict';
// Reference coordinates and matching metric are from 8values (MIT).
// Russian descriptions and the two projections are editorial additions.
const ideologyTranslations={
'Anarcho-Communism':'Анархо-коммунизм','Libertarian Communism':'Либертарный коммунизм','Trotskyism':'Троцкизм','Marxism':'Марксизм','De Leonism':'Делеонизм','Leninism':'Ленинизм','Stalinism/Maoism':'Сталинизм / маоизм','Religious Communism':'Религиозный коммунизм','State Socialism':'Государственный социализм','Theocratic Socialism':'Теократический социализм','Religious Socialism':'Религиозный социализм','Democratic Socialism':'Демократический социализм','Revolutionary Socialism':'Революционный социализм','Libertarian Socialism':'Либертарный социализм','Anarcho-Syndicalism':'Анархо-синдикализм','Left-Wing Populism':'Левый популизм','Theocratic Distributism':'Теократический дистрибутизм','Distributism':'Дистрибутизм','Social Liberalism':'Социальный либерализм','Christian Democracy':'Христианская демократия','Social Democracy':'Социал-демократия','Progressivism':'Прогрессивизм','Anarcho-Mutualism':'Анархо-мютюэлизм','National Totalitarianism':'Национальный тоталитаризм','Global Totalitarianism':'Глобальный тоталитаризм','Technocracy':'Технократия','Centrist':'Центризм','Liberalism':'Либерализм','Religious Anarchism':'Религиозный анархизм','Right-Wing Populism':'Правый популизм','Moderate Conservatism':'Умеренный консерватизм','Reactionary':'Реакционное направление','Social Libertarianism':'Социальное либертарианство','Libertarianism':'Либертарианство','Anarcho-Egoism':'Анархо-эгоизм','Nazism':'Нацизм','Autocracy':'Автократия','Fascism':'Фашизм','Capitalist Fascism':'Капиталистический фашизм','Conservatism':'Консерватизм','Neo-Liberalism':'Неолиберализм','Classical Liberalism':'Классический либерализм','Authoritarian Capitalism':'Авторитарный капитализм','State Capitalism':'Государственный капитализм','Neo-Conservatism':'Неоконсерватизм','Fundamentalism':'Фундаментализм','Libertarian Capitalism':'Либертарианский капитализм','Market Anarchism':'Рыночный анархизм','Objectivism':'Объективизм','Totalitarian Capitalism':'Тоталитарный капитализм','Ultra-Capitalism':'Ультракапитализм','Anarcho-Capitalism':'Анархо-капитализм'};
const ideologyName=i=>ideologyTranslations[i.name]||i.name;
const profileKeys=['econ','dipl','govt','scty'];
function validPoliticalScores(scores){return scores&&profileKeys.every(k=>typeof scores[k]==='number'&&Number.isFinite(scores[k])&&scores[k]>=0&&scores[k]<=100);}
function nearestIdeologies(scores){
 if(!validPoliticalScores(scores))return [];
 return politicalIdeologies.map((ideology,index)=>({ideology,index,distance:profileKeys.reduce((sum,key)=>sum+Math.abs(ideology.stats[key]-scores[key])**(['econ','govt'].includes(key)?2:1.73856063),0)})).sort((a,b)=>a.distance-b.distance||a.index-b.index);
}
function politicalCoordinates(s){return {economy:(50-s.econ)/5,authority:(50-s.govt)/5,nation:(50-s.dipl)/5,progress:(s.scty-50)/5};}
const coordinateText=n=>(n>0?'+':'')+(Math.abs(n)<.005?0:n).toFixed(2).replace('.',',');
const percentText=n=>Number(n.toFixed(1)).toLocaleString('ru-RU');
const politicalInterpretations={
 econ:{center:'Экономический центр: ответы распределены почти поровну между равенством и рынком.',high:'Приоритет уменьшения экономического неравенства, перераспределения и общественных услуг.',low:'Приоритет свободного рынка, частной инициативы и ограничения экономического вмешательства.'},
 dipl:{center:'Международное сотрудничество и национальные интересы получают сопоставимый вес.',high:'Приоритет международного сотрудничества и учёта интересов людей за пределами своей страны.',low:'Приоритет национальных интересов и самостоятельности государства в международных отношениях.'},
 govt:{center:'Личная автономия и полномочия власти получают сопоставимый вес.',high:'Приоритет личной автономии, гражданских свобод и ограничений государственной власти.',low:'Приоритет порядка, контроля и более широких государственных полномочий.'},
 scty:{center:'Баланс между пересмотром общественных норм и сохранением традиций.',high:'Готовность пересматривать общественные нормы и расширять пространство допустимых способов жизни.',low:'Приоритет преемственности и сохранения традиционных общественных норм.'}
};
function interpretPoliticalAxis(key,value){const text=politicalInterpretations[key];if(value>=45&&value<=55)return text.center;const amount=Math.abs(value-50)>=20?'Выраженный уклон. ':'Умеренный уклон. ';return amount+(value>50?text.high:text.low);}
function politicalSynthesis(s){
 let text='';
 if(s.econ>=60&&s.govt>=60)text='В этом профиле уменьшение экономического неравенства сочетается с защитой личной свободы. Социальные гарантии и ограничение контроля над частной жизнью могут быть частями одной позиции.';
 else if(s.econ>=60&&s.govt<=40)text='В этом профиле экономическое перераспределение сочетается с поддержкой более сильной власти. Для уточнения позиции полезно различить полномочия в экономике и пределы контроля над частной жизнью.';
 else if(s.econ<=40&&s.govt>=60)text='В этом профиле рыночная самостоятельность сочетается с гражданскими свободами. Общий мотив — ограничить принуждение в экономической и личной жизни.';
 else if(s.econ<=40&&s.govt<=40)text='В этом профиле поддержка рынка сочетается с сильными государственными полномочиями. Экономическая свобода и личная автономия здесь получают разный вес.';
 else text='Экономика, гражданские свободы и культурные нормы здесь не складываются в один простой выбор «лево или право». Рассматривайте каждую шкалу отдельно: близость к центру может означать как умеренные, так и взаимно компенсирующие ответы.';
 const strongest=profileKeys.map(key=>({key,weight:Math.abs(s[key]-50)})).sort((a,b)=>b.weight-a.weight)[0];
 if(strongest.weight>=20){const labels={econ:s.econ>50?'экономическое равенство':'рыночная самостоятельность',dipl:s.dipl>50?'международное сотрудничество':'национальные интересы',govt:s.govt>50?'личная автономия':'полномочия власти',scty:s.scty>50?'обновление общественных норм':'сохранение традиций'};text+=' Один из наиболее выраженных приоритетов — '+labels[strongest.key]+'.';}
 return text;
}
let profileState={scores:null,selected:0,all:false};
const referenceDefaults=['Centrist','Social Democracy','Libertarian Socialism','Classical Liberalism','Libertarianism','Conservatism','State Socialism','Autocracy'];
function profileReferences(){return politicalIdeologies.map((ideology,index)=>({ideology,index})).filter(r=>profileState.all||referenceDefaults.includes(r.ideology.name)||r.index===profileState.selected||nearestIdeologies(profileState.scores).slice(0,3).some(n=>n.index===r.index));}
const plotSpecs=[{id:'economy',title:'Экономика и власть',x:'economy',y:'authority',left:'Равенство',right:'Рынок',top:'Полномочия власти',bottom:'Личная автономия'},{id:'society',title:'Международные и общественные приоритеты',x:'nation',y:'progress',left:'Сотрудничество',right:'Нация',top:'Прогресс',bottom:'Традиция'}];
function profilePlot(spec){
 const s=profileState.scores,point=politicalCoordinates(s),selected=politicalIdeologies[profileState.selected],other=politicalCoordinates(selected.stats),px=x=>70+(x+10)*15,py=y=>55+(10-y)*15;
 const groups=new Map();for(const r of profileReferences()){const c=politicalCoordinates(r.ideology.stats),key=c[spec.x]+','+c[spec.y];if(!groups.has(key))groups.set(key,{x:c[spec.x],y:c[spec.y],members:[]});groups.get(key).members.push(r);}
 let shapes='<rect x="70" y="55" width="150" height="150" fill="#eaf0e5"/><rect x="220" y="55" width="150" height="150" fill="#f0e9dd"/><rect x="70" y="205" width="150" height="150" fill="#edf1ef"/><rect x="220" y="205" width="150" height="150" fill="#f3eee7"/>';
 for(const n of [-10,-5,0,5,10])shapes+=`<path d="M ${px(n)} 55 V 355 M 70 ${py(n)} H 370" stroke="${n===0?'#7c887e':'#cdd5ca'}" stroke-width="${n===0?1.6:1}"/><text x="${px(n)}" y="378" text-anchor="middle">${n>0?'+':''}${n}</text><text x="56" y="${py(n)+5}" text-anchor="end">${n>0?'+':''}${n}</text>`;
 shapes+=`<path d="M ${px(point[spec.x])} 355 V ${py(point[spec.y])} H 70" stroke="#254f38" stroke-dasharray="4 5" opacity=".5"/><path d="M ${px(point[spec.x])} ${py(point[spec.y])} L ${px(other[spec.x])} ${py(other[spec.y])}" stroke="#9c7429" stroke-dasharray="3 5"/>`;
 const legend=[];let number=0;
 for(const group of groups.values()){
  const label=++number,active=group.members.some(m=>m.index===profileState.selected),current=active?profileState.selected:group.members[0].index;
  const names=group.members.map(m=>ideologyName(m.ideology)).join(' / ');
  shapes+=`<g data-reference="${current}" tabindex="0" role="button" aria-label="${esc(names)}: X ${coordinateText(group.x)}, Y ${coordinateText(group.y)}"><title>${esc(names)}</title><circle cx="${px(group.x)}" cy="${py(group.y)}" r="21" fill="transparent"/><circle cx="${px(group.x)}" cy="${py(group.y)}" r="12" fill="${active?'#986921':'#65716a'}" stroke="white" stroke-width="2"/><text x="${px(group.x)}" y="${py(group.y)+4}" text-anchor="middle" class="reference-number">${label}</text></g>`;
  legend.push(`<li><span>${label}.</span> ${group.members.map(m=>`<button data-reference="${m.index}" aria-pressed="${m.index===profileState.selected}">${esc(ideologyName(m.ideology))}</button>`).join(' / ')}</li>`);
 }
 shapes+=`<g class="your-point" pointer-events="none"><circle cx="${px(point[spec.x])}" cy="${py(point[spec.y])}" r="18" fill="none" stroke="#214f35" stroke-width="3"/><path d="M ${px(point[spec.x])-7} ${py(point[spec.y])} H ${px(point[spec.x])+7} M ${px(point[spec.x])} ${py(point[spec.y])-7} V ${py(point[spec.y])+7}" stroke="#214f35" stroke-width="4"/></g>`;
 return `<section class="profile-plot"><h4>${spec.title}</h4><p class="plot-coordinates">Вы: X <strong>${coordinateText(point[spec.x])}</strong> · Y <strong>${coordinateText(point[spec.y])}</strong></p><svg viewBox="0 0 440 440" role="group" aria-labelledby="${spec.id}PlotTitle"><title id="${spec.id}PlotTitle">${spec.title}. Ваша точка: X ${coordinateText(point[spec.x])}, Y ${coordinateText(point[spec.y])}. Нажмите ориентир для сравнения.</title><text x="220" y="24" text-anchor="middle" class="axis-end">${spec.top} ↑</text>${shapes}<text x="70" y="405" text-anchor="start" class="axis-end">← ${spec.left}</text><text x="370" y="405" text-anchor="end" class="axis-end">${spec.right} →</text><text x="220" y="433" text-anchor="middle" class="axis-end">${spec.bottom} ↓</text></svg><details class="plot-key"><summary>Обозначения направлений (${number})</summary><ol>${legend.join('')}</ol></details></section>`;
}
function profileExplorer(){
 const s=profileState.scores,reference=politicalIdeologies[profileState.selected];
 return `<h4>Ваше положение среди направлений</h4><p class="small">Зелёное кольцо с крестом — вы. Золотая точка — выбранное направление. Серые точки — другие ориентиры. Нажмите точку или выберите направление в списке.</p><div class="profile-controls"><label for="ideologySelect">Сравнить с направлением<select id="ideologySelect">${politicalIdeologies.map((i,index)=>`<option value="${index}" ${index===profileState.selected?'selected':''}>${esc(ideologyName(i))}</option>`).join('')}</select></label><label class="profile-all"><input id="allIdeologies" type="checkbox" ${profileState.all?'checked':''}> Все ${politicalIdeologies.length} направления</label></div><div class="profile-plots">${plotSpecs.map(profilePlot).join('')}</div><div class="profile-comparison" role="status"><p>Сравнение: <strong>${esc(ideologyName(reference))}</strong></p><div class="profile-table-wrap"><table><thead><tr><th scope="col">Шкала</th><th scope="col">Вы</th><th scope="col">Ориентир</th><th scope="col">Разница</th></tr></thead><tbody>${politicalAxes.map(([key,,left])=>`<tr><th scope="row">${left}</th><td>${percentText(s[key])}%</td><td>${percentText(reference.stats[key])}%</td><td>${coordinateText(s[key]-reference.stats[key])} п. п.</td></tr>`).join('')}</tbody></table></div></div><p class="small">Точки направлений — условные ориентиры авторов 8values, а не результаты опроса их сторонников. Совпадение на одной плоскости не означает совпадения по всем четырём шкалам. Совпавшие ориентиры объединены под одним номером; выбрать каждый можно в списке или обозначениях.</p>`;
}
function renderPoliticalProfile(scores,neutral=false){
 if(!validPoliticalScores(scores))return '';
 const nearest=nearestIdeologies(scores),best=nearest[0],ties=nearest.filter(n=>Math.abs(n.distance-best.distance)<1e-8),shown=nearest.slice(0,Math.max(3,ties.length));
 profileState={scores:{...scores},selected:best.index,all:false};
 return `<section class="political-profile"><div class="profile-verdict"><p class="eyebrow">Ближайший профиль по алгоритму 8values</p><h4>${esc(ties.map(n=>ideologyName(n.ideology)).join(' / '))}</h4>${ties.length>1?'<p>Несколько ориентиров оказались на одинаковом расстоянии.</p>':''}<p>${esc(politicalSynthesis(scores))}</p>${neutral?'<p><strong>Все ответы нейтральны или неопределённы.</strong> Центральная точка в этом случае не подтверждает центристских убеждений.</p>':''}<p class="small">Это приблизительное сопоставление политических ответов, а не оценка личности.</p></div><div class="profile-interpretations">${politicalAxes.map(([key,title])=>`<p><strong>${title}.</strong> ${esc(interpretPoliticalAxis(key,scores[key]))}</p>`).join('')}</div><h4>Ближайшие ориентиры по четырём шкалам</h4><div class="nearby-ideologies">${shown.map((n,i)=>`<button data-reference="${n.index}"><span>${i+1}</span>${esc(ideologyName(n.ideology))}</button>`).join('')}</div><div id="profileExplorer">${profileExplorer()}</div><details class="profile-method"><summary>Как получены ярлык и координаты</summary><p>Ближайший профиль выбирается по исходному алгоритму 8values: |Δ экономики|² + |Δ свободы|² + |Δ международной шкалы|^1,73856063 + |Δ прогресса|^1,73856063. Чем меньше сумма, тем ближе ориентир. Сравнение учитывает все четыре шкалы; это не процент совпадения.</p><p>Координаты от −10 до +10 — проекция результатов 8values, созданная для атласа. На первой карте X = (50 − равенство) / 5, Y = (50 − свобода) / 5. На второй X = (50 − мир) / 5, Y = (прогресс − 50) / 5. Ноль означает 50% на исходной шкале. Это не координаты официального Political Compass.</p><p>В текстовой расшифровке 45–55% названы балансом, отклонение менее 20 пунктов от 50% — умеренным, от 20 — выраженным. Это редакционные интервалы, не научные пороги.</p><p><a href="https://github.com/8values/8values.github.io/blob/master/ideologies.js" target="_blank" rel="noopener noreferrer">Исходные ориентиры ↗</a> · <a href="https://github.com/8values/8values.github.io/blob/master/results.html" target="_blank" rel="noopener noreferrer">Алгоритм 8values ↗</a></p></details></section>`;
}
function selectProfileReference(index){if(!profileState.scores||!Number.isInteger(index)||!politicalIdeologies[index])return;profileState.selected=index;$('#profileExplorer').innerHTML=profileExplorer();}
$('#compassView').addEventListener('click',e=>{const b=e.target.closest('[data-reference]');if(b)selectProfileReference(Number(b.dataset.reference));});
$('#compassView').addEventListener('keydown',e=>{const b=e.target.closest('g[data-reference]');if(b&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectProfileReference(Number(b.dataset.reference));$('#ideologySelect').focus();}});
$('#compassView').addEventListener('change',e=>{if(e.target.id==='ideologySelect'){selectProfileReference(Number(e.target.value));$('#ideologySelect').focus();}else if(e.target.id==='allIdeologies'){profileState.all=e.target.checked;$('#profileExplorer').innerHTML=profileExplorer();$('#allIdeologies').focus();}});
